#+TITLE: 5 Learning Thoery
#+AUTHOR: Ben Heinze
#+DATE: 2026-09-14
#+STARTUP: noindent

#+MACRO: hl @@html:<span class="hl-$1">$2</span>@@@@latex:\hl{$1}{$2}@@

# This is used to shrink the pdf page margins
#+LATEX_HEADER: \usepackage[left=0.75in,right=0.75in,top=1in,bottom=1in]{geometry}

# This is used to shrink the spacing between bullet points
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[itemize]{itemsep=2pt, topsep=4pt}

* K-Medoids

Representative object or member of a data set 

Different objective fucntions:

- K-means: find centroids of clusters that minimize the distance from the points to their clusters
- K-Medoids: Same thing as k means, but instead of looking at a distance from an arbitrary centroid, we look at the distance to the representative sample from the dataset. 
Medoid is like a median: we reduce the influence of outliers

** Partitioning Around Medoids (PAM)

{{{hl(yellow,insert psuedocode here)}}}

1. Select medoids at random
2. get min distance from xi in dataset from medoids like k-means 
3. Find the points that minimize distortion by brining those points closer to the medoids (i think)

The partition comes from dividing the data up by

** Fuzzy c-Means

A method to create "fuzzy" clusters, where $f$ is a level of "fuzzification" in the range (1,$\infty$)

Fuzzy: instead of assigning datapoints to clusters in a binary scenario, you have a "degree of membership" between the two clusters. The degree of membership algorithmically becomes a weighting function.

- $f \to 1$ makes clusters more "crisp"
- $f \to \infty$ makes clusters more "fuzzy"

The weighting function looks like a kernel function. 

* Cluster Evaluation 

{{{hl(red,Clustering does not equal Classification)}}}

- Evaluating clusters using classification metrics is *not valid*. You need to consider the geometry of the clusters found. 
- the principal 'preference bias' is to find clusters where:
  - clusters are well separated in distance 
  - members of clusters are "close" to one another

One measurement of cluster validity is to divide cohesion by separation

- Cohesion: {{{hl(orange,add equation here)}}}
- Separation: {{{hl(orange,add equation here)}}}


** Cluster Sum Squared Error

Name is deceptive because of the term "error". 

{{{hl(orange,COME BACK LATER)}}}

** Pseudo-F 

Calinski-Harabasz measure, derived from ANOVA

** Silhouette Coefficient

Fir each datapoint, calculate the average distance between that point and every other point in that cluster. For each data point, find the minimum average distance to the points in each of the other clusters not containing xi. The, for each point xi, calculate silhouette coefficient.

{{{hl(orange,COME BACK LATER)}}}


** Rand Index


** Adjusted Rand Index 

** Dunn Index 

Provides a cluster "validity" score based on the number of clusters. The max Dunn index over different nubmers of clusters can be used to determine an appropriate number of clusters

* Leader Clustering

Ideally, we would like tot adapt the number of clusters needed rather than tuning it. 

/Leader clustering Algorithm/ considers the distance of an example from the existing clusters. If that distance exceeds a threshold (which is tunable), a new cluster is created. If there is a cluster with a large number of examples greater than $\theta$, the reference vectors re duplicated and perturbed and members reassigned to the new clusters. 


* Version Spaces 

Hypothesis: some type of model
Hypothesis $h$ is {{{hl(red,consistent)}}}, with examples $\mathcal{D} \iff h(x) = c(x)$  for each example in $\mathcal{D}$.


\(
  \text{consistent}(h,\mathcal{D}) \equiv (\forall <x, c(x)> \in \mathcal{D}, h(x) = c(x)
\)

Version space $VS(h, \mathcal{D})$ is the subset of all hypotheses kn $\mathcal{H}$ that are consistent with the training examples $\mathcal{D}$


** Representing Version Spaces

Key idea: version spaces can be represented by only keeping track of maximally general $(G)$ and maximally specific $(S)$ members of $VS(h, \mathcal{D})$.

Every member of the version space lies between these boundaries.

** Candidate Elimination Algorithm 

- Initialize $G$ to the set of maximally general hypotheses in $\mathcal{H}$
- Initialize $S$ to the set of maximally specific hypotheses in $\mathcal{H}$

Consider both positive and negative examples.

Add algorithm here
{{{hl(orange,COME BACK LATER)}}}

Shows Trace example


* Version Spaces

Slow to converge

Candidate elimination has no preference bias since it keeps track of all consistent hypotheses

However that consistency entails an assumption that all examples are labeled correctly (no noise)

* Computational Learning Theory

- What general laws constrain inductive learning?
- What learning problem can we solve?
- when can we trust the output of a learning algorithm?
  - {{{hl(orange,COME BACK LATER)}}} 

- Our goal is to create *Models* of learning


* Learning Models

When specific learning, we need to consider:
1. Who is the learner?
2. Whats the problem domain?
3. Where does experience come from?
4. Is any prior knowledge available?
5. What are the performance criteria?



* Typical Concept Learning Task

- Given 
  - Instance space $\mathcal{X}$
  - Target function $c$
  - Hypothesis $\mathcal{H}$
  - Training examples $\mathcal{D}$
- Determine 
  - Hypothesis $h \in \mathcal{H}$ such that $h(x) = c(x), \forall x \in \mathcal{D}$ (memorize training data)
  - Hypothesis $h \in \mathcal{H}$ such that $h(x) = c(x), \forall x \in \mathcal{X}$ (generalize to unseen data)

* Notation 

| $\mathcal{C}$| Class of possible concepts|
| $\mathcal{X}$ | Set of instances |
| $n$ | Length of each instance|
| $\mathcal{L}$ |Learner |
| $\mathcal{H}$ | Hypotheis space |
| $\epsilon$ | error parameter |
| $\delta$ |confidence parameter (excess error probability bound) |
| $size(c)$ | encoding length of $c$, assuming some representation (aka description length)|



* Sample Complexity

sample complexity: a measure of how many training examples are sufficient to learn the target concept. Tepends on how we get out examples.
- Active learning 
- Passive learning from teacher-annotated examples 
- Passive learning from teacher-selected examples ({{{hl(orange,COME BACK LATER)}}} expand)

** Active Learning

learner proposes instance $x$
- teacher provides $c(x)$
  - comprehensiveness: assume $c$ is in learner's hypothesis space $\mathcal{H}$
  - query is a form of inductive bias (sometimes non-trivial)
- optimal query strategy: play 20 questions
  - Keep choosing an instance $x$ that splits the hypothesis search space $VS(\mathcal{H}, \mathcal{D})$ in half

** Teacher Annotated 

- Given $\mathcal{D}$, $\mathcal{H}$, $\mathcal{C}$, and training instances generated by a fixed, unknown probability distribution $\mathcal{P}$ over $\mathcal{X}$
- Learner Observes a sequence drawn from $\mathcal{P}$
  - $\mathcal{D}$: examples of form <x, c(x)> for target concept $c$
  - instances $x \in \mathcal{D} \tilde \mathcal{P}$
  - teacher provides target value $c(x)$ for each
- Learner must output hypothesis $h$ estimating $c$

** Teacher Selected

- Teacher provides training samples
- Optimal teacher is sometimes called a "helpful" teachers
- Optimal teaching strategy deponds upon $\mathcal{H}$ used by learner

** N Boolean Attributes 

If $n$ possible Boolean attributes in $\mathcal{H}$, $n + 1$ examples suffice. You can divide the search space for a boolean classification in half by giving the learner one good example.

- Helpful teacher could aid learner in acquiring concept in at most n+1 examples (could be less).


* True Error
/True error/ ($error_{\mathcal{P})}$):  {{{hl(orange,COME BACK LATER)}}}

- Training error:

** Exhausting Version Space 
Version space is said to be $\epsilon$-exhausted w.r.t. $c$ and $\mathcal{D}$ if every hypothesis $h$ in the version space has true error less than $\epsilon$ w.r.t. $c$ and $\mathcal{D}$.


*Haussler Theorem*: If the hypothesis space $\mathcal{H}$ is finite, and $\mathcal{D}$ is a sequence of $m \geq 1$ indipendent random examples of some target concept $c$, then for any $0 \leq \epsilon \leq 1$, the probibaility that the version space w.r.t. $\mathcal{H}$ and $\mathcal{D}$ is not e-exhauseted (w.r.t. c) ... {{{hl(orange,COME BACK LATER)}}}


** Number of required examples:

Using Haussler's theorem, we can create the inequality:

\(
  m \geq \frac{1}{\epsilon} \left( ln|\mathcal{H}| + ln \frac{1}{\delta} \right)
\)


** Conjnuctions of boolean literals

Using Haussler's theorem, if we assume conjunctions of ocnstraints on up to $n$ Boolean attributes, then $|\mathcal{H}| = 3^{n}$. Why $3^{n}$? It can take on three values: true, false, and dont care. 


thus,


\(
  m \geq \frac{1}{\epsilon} \left( ln|3^{n}| + ln \frac{1}{\delta} \right)
\)


* Agnostic Learning

So far, we assumed $c \in \mathcal{H}$. For agnostic learning, we don't assume this. Instead, we attempt to find the clsoest hypothesis possible. Sample complexity is 


\(
  m \geq \frac{1}{2 \epsilon^{2}} \left( ln|\mathcal{H}| + ln \frac{1}{\delta} \right)
\)




* PAC Learning 

Probably approximately Correct 

pac learnable means efficient

* VC Dimension 

- provides a measure of expressiveness of infinite hypothesis spaces 

What is it?
- define a partition. There is a type called a dichotomy partition (split it into two). 

{{{hl(orange,COME BACK LATER)}}}  

Shattering: 



Model selection: we saw theneed for inductive bias correstionding to assumptions about $\mathcal{H}$.
Many consider the VC dimension as the strength of the inductive bias. 


** Tripe Tradeoff
- Complexeicty of $\mathcal{H}$
- Training set size, $N$
- Generalization error, $E$, on new data

How do we balance all of this?



** VC(H) and Inductive Bias 
- Unbiased hypothesis space $\mathcal{H}$ shatters the entire instance space $X$ since it includes all possible hypotheses 
- AKA, $\mathcal{H}$ is able to induce every partition on set $X$ of all possible instances (regardless of the set $X$)
- the larger the subset $X$ that can be shattered, the /more expensive/ a hypothesis space is (i.e., the less biased). 






** VC(H) and Sample Complexity 

- VC(H) prescribes an Occam algorithm for infinite hypothesis spaceas 












