* Day 1 
Holy shit, what a concert. This festival day one was amazing. We rode bird scooters to the venue and got there in 5 minutes, bought some merch, and saw so many shows. In order, these are the bands I saw
- Winona Fighter
- Last song of LOLO
- VANA
- a little of Jinjer
- Some Good Sleepy
- Some Suicide Silence
- Listened to the first few notes of Hot Mulligan (I tried but just couldn't do it)
- Sleeping With Sirens
- South Arcade
- Some The Ghost Inside
- Dance Gavin Dance

Right off the bat Anthony and I separated to go see different bands. WInona
Fighter was really good but the vocals were a little quiet. She had fantastic
energy, but it was still the first concert of the day so the audience wasn't
warmed up yet. Anthony and I started walking away from LOLO's concert, but we
heard a really good scream from a stage, turned around to see what was going
on, made eye contact, then bolted to see them play. It was a band we've never
heard of, but VANA was sooo good. The pit was crazy too. We went into a lot of
mosh pits. Anthony is definitely braver than I am in some of those because
sometimes people were fulll fledged thrashing around, punching and kicking and
spinning.. Not something I want to deal with. Anthony was excited to see Hot
Mulligan. I was still separated from him but I went anyways to give them a
shot. I got pretty deep into the crowd too, but as soon as he started singing,
I noped out of there. I really just hate his voice so much lol. Sleeping with
Sirens was super good, they got cut off on the very end of their last song. It
wasn't the best though because Anthony and waited at the wrong stage, so when
we got to the stage our view kinda sucked since there was big ass camera crane
in front of us because Amazon Prime was livestreaming it. SOUTH ARCADE WAS SOOO
GOOD. The crowd was so energetic, we moshed every time. I got a few clips of
songs I really like, but I cut then short so I can go mosh. We saw The Ghost
Inside as we were waiting for DGD to get on stage but I was super impressed so
I gotta look them up later. Then there was DGD... Oh. My. God. Their set list
was small since they played at 9:20 and curfew was 10, but OH MY GOD THEY WERE
FANTASTIC. This was by far the craziest, largest, most into-DGD crowd I've ever
seen. That was by far the craziest mosh of the night for me. I got thrown
around so much I ended up in every section of that crowd; the current takes you
where it wants. I was absolutely drenched in sweat, most of which wasn't even
mine. I was slammed up against people, thrown around, caught some girl before
she fell to the ground, and i am so sore now lol. Right before they started
playing All The Way Down, everything was calm around me. As soon as Will hit
the intro riff, the pit just erupted into existence, and I was right in the
middle of it. I've seen DGD multiple times now, and although their concert was
short, holy hell it was by far the most energetic and crazy one I've seen so
far. 11/10 would do again.


* Day 2

Today was even better. We put more effort into keeping sunscreen around the clock, staying hydrated and sitting to cool off, but we still say everyone we wanted. Im tired so im not going to go as specific this time for the details, but I saw
- Haywire
- Bayside
- Dying Wish
- Origami Angel
- First couple songs of G-Eazy (he wasnt really doing anything so I left to find a better performer)
- Boundaries
- First 20 minutes of Breathe Caroline
- Scary Kids Scaring Kids
- We Came As Romans
- Silverstein
- Papa Roach

it was fantastic. we got raising canes after. I was aching everywhere lol.
