#+TITLE: Nonparametric Learning
#+AUTHOR: Ben Heinze
#+DATE: 2026-08-31
#+STARTUP: noindent

#+MACRO: hl @@html:<span class="hl-$1">$2</span>@@@@latex:\hl{$1}{$2}@@

# This is used to shrink the pdf page margins
#+LATEX_HEADER: \usepackage[left=0.75in,right=0.75in,top=1in,bottom=1in]{geometry}

# This is used to shrink the spacing between bullet points
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[itemize]{itemsep=2pt, topsep=4pt}

* Classification
 
 Suppose we are presented with a query point $x_{q}$, and want to know the class to which it belongs

A probabilistic approach:
\(
  c = \underset{c \in C}{\arg\max} P(c \mid x_q)
\)


where we use Bayes rule:

\(
  P(c \mid x_{q}) = \frac{P\left( x_q \mid c \right)P(c)}{P\left( x_q \right)} = \frac{P\left( x_q \mid c \right)P(c)}{\sum_{c' \in C}^{} P(x_q \mid c') P(c')}
\)

* Parzen Window Classification

- Given X = data
- find the class to which query point $x_{q}$ belongs
- the nearest neighbor rule states:  {{{hl(orange,COME BACK LATER)}}}


\[
  H(u) =\begin{cases}
    1 & |u_{j}| < \frac{1}{2}, j=1,\ldots, d \\
    0 & \text{otherwise}
  \end{cases}
\]


* K-nearest neighbor Estimation
- Doesn't need to fix the size of the bin
- The parameter $k$ specifies how many of the neighbors are used in the estimate
- $D(x,x^{t})$: distance function between $x$ and $x^{t}$
  - Distance to the k-the neighbor. It determines the size of the bin 

* Voronoi Diagram

A way to section off the data space as regions that represent classes. Then, you ask which region the point is in to determine its class

* Distance Metrics

- Metric Spaces
  1. Non-negative: $D(x,y) \geq 0$
  2. Reflexive: $D(x,y) =0 \iff x=y$
  3. Symmetric: $D(x,y) = D(y,x)$
  4. Triangle Inequality: $D(x,y) + D(y,z) \geq D(x,z)$

*Minkowski distance* ($L^{p}$ norm) is typically used to measure the distance between a query point $x_q$ to an example point $x_j$:
\[
  D_{p}(x, y) = (\sum_{i=1}^{d} |x_{i}-y_{i}|^{p})^{\frac{1}{p}}
\]
- $p=1$: Manhattan distance: used when dimensions don't have similar properties (age, weight, gender)
- $p=2$: Euclidean distance: used when dimensions have similar properties (width, height, depths)
- Boolean values have Hamming distance
- Max-coordinate Distance: $D_{\infty}(x,y) = \max_{i}|x_{i} - y_i|$

* Calculating Distance for Categorical Data 

1. *one-hot encoding may not work as well for ordinal data, since some categories have implied order: (months of a year). In the report, write your assumptions*
2. Value Difference Metric (only works for classification). It takes a probabilistic approach. *Explain Here*. 

* Mixing data types

You can mix numerical and categorical distances with specific methods. You already know this


* Creating an Experiment

When writing a hypothesis, narrow the scope of your hypothesis, and be specific about which metrics you are testing. It must be numerically testable. 

 Testable Measures include:
- Accuracy
- Precision, recall, F1
- Cross entropy
- Area under the ROC curve (AUC)
- MSE 
- MAE

he goes on about conducting a proper experiment. 

* Week 2 


* Confusion Matrices

suppose we have two classes:

| x| Actual true|Actual False|
|*predicted true*| # true positives|# false positives|
|*predicted false*|# False negatives| # true negatives|

\[ \text{Error:} \frac{FP+FN}{TP+TN+FP+FN}\]

Precision: \[\frac{TP}{TP+FP}\]
- The proportion of items predicted as positive that are actually positive 


Recall = \[\frac{TP}{TP+FN}\]
- The proportion of actually positive items that were correctly predicted as positive
\[
  F_{\beta} = (1+ \beta^{2}) \cdot \frac{precision \cdot recall}{\beta^{2} \cdot precision+recall},
  \text{usually } \beta=1: F_{1}=2 \cdot \frac{precision \cdot recall}{Precision+recall}
\]

** Confusion Matrices

3-class problem:

|                   | Actual Class 1 | Actual class 2 | Actual class 3 |
| Predicted class 1 | 15             | 2              | 4              |
| Predicted class 2 | 3              | 12             | 1              |
| Predicted class 3 | 4              | 2              | 17             |

Recall: the proportion of actually positive items that were correctly predicted as positive (TP / (TP + FN)).

Example:
- $TP_1 = 15$
- $TN_1 = 32$
- $FN_1 = 7$
- $FP_1 = 6$


- Micro-averaging: preferred, but you lose info. {{{hl(orange,Add formula)}}}
- Macro-averaging: {{{hl(orange,add formula)}}}


* Hyperparameter Search

| Char                                    | Def                                                       |
| $\lambda$                               | set of Hyperparameters to be used by the search algorithm |
| $A$                                     | Algorithm used to optimize/search                         |
| $F$                                     | loss function                                             |
| $M$                                     | Model                                                     |
| $\mathbb{x}^{tr}$ and $\mathbb{x}^{te}$ | training and test examples                                |



** Grid Search (Factorial Study)

Tries a set of different values. Gets very expensive as you test more values

** Random Search

Select random combos for hyperparameters. Better than grid search 

** Random Search (Hill Climb)

Choose a random point, keep climbing up to the nearest local minimum. Elitist approach. Simulated Annealing is a better variant.


* k-NN Classifier

- may need to examine all examples in $E$ (training set)
- each comparison involves computing $D(e, x_{q}) \forall e \in E$ which requires $O(d)$ calculations for $d$ dimensions
- Worst-case performance for naive nearest neighbor search is $O()$
{{{hl(orange,COME BACK LATER)}}}

** Edited Nearest neighbor v1

- "editing" is similar to stepwise backward elimination in features selection
Removes misclassified examples from dataset
1. for each $x^{t} \in X$ do 
  1. classify $x^{t}$ using 1-nn on $X\backslash \{x^{t}\}$ 
  2. compare class returned to true class of $x^{t}$
  3. if disagree, remove $x^{t}$ from $X$
2. Repeat until performance degrades on separate validation data set


** Edited Nearest neighbor v2

Second approach removes correct examples
1. for each $x^{t} \in X$ do 
  1. classify $x^{t}$ using 1-nn on $X\backslash \{x^{t}\}$ 
  2. compare class returned to true class of $x^{t}$
  3. if agree, remove $x^{t}$ from $X$
2. Repeat until performance degrades on separate validation data set
 


** Condensed Nearest neighbor


Time and space complexity increase as the dataset increases. To account for this, a /condensing/ method is used to shrink the dataset without degrading performance. Select the smallest subset $\mathcal{Z}$ of $\mathcal{X}$ such that when $\mathcal{Z}$ is used in place of $\mathcal{X}$, error doesn't increase.

#+BEGIN_LATEX 
\noindent
\mathcal{Z} \gets \emptyset \\
Repeat \\
For all x \in \mathcal{X} (in random order) \\  
\indent find x' \in \mathcal{Z} such that ||x-x'|| = $\min_{x^j \in \mathcal{Z}||x-x^j||}$ \\
\indent If class(x) \neq class(x') add x to \mathcal{Z} \\
until \mathcal{Z} does not change \\
#+END_LATEX

Condensed nearest neighbor is a greedy algorithm that aims to minimize training error and complexity, measured by the size of the stored subset.

To adapt this to regression, we can define a threshold.

* KD-Tree

You can reduce the average complexity to $O(d \log |E|)$ by sorting distance to find nearest neighbors. 

When we plot a point down on the search space, we can define a nearest neighbor by a region. Look up /ranch-and-bound search/ for details. We won't be implementing this



































