#+TITLE: 3 Density Estimation and Kernsls
#+AUTHOR: Ben Heinze
#+DATE: 2026-08-29
#+STARTUP: noindent

#+MACRO: hl @@html:<span class="hl-$1">$2</span>@@@@latex:\hl{$1}{$2}@@

# This is used to shrink the pdf page margins
#+LATEX_HEADER: \usepackage[left=0.75in,right=0.75in,top=1in,bottom=1in]{geometry}

# This is used to shrink the spacing between bullet points
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[itemize]{itemsep=2pt, topsep=4pt}


* Outlier Detection

Outlier detection is often an "unsupervised learning" process

** Local Outlier factor

Outliers are typically sparse
- compare local density of a datapoint with average local density of other data points

\[
  LOF(x) = \frac{\delta_{k}(x)}{\sum_{s \in \mathcal{N}(x)}^{} \delta_{k}(s)/|\mathcal{N}(x)|}
\]

| $\delta_{k}(x)$ | distance between instance x and kth nn |
|        $\mathcal{N}(x)$          |      {{{hl(orange,COME BACK LATER)}}}                                  |


* Error in Nearest Neighbor

Errors are introduced for multiple reasons:
- noise
- lack of precision
- human Error
- irrelevant attributes

For continuous concepts, at best, an example is an approximation


* Dimensionality Reduction
Two principal categories:
- Feature selection: choosing a subset of features
- feature extraction: transform input features to a new feature space

Example transformation: Fourier Transform
- Data is often provided in the "time" domain
- Data is converted to the "frequency" domain
- Example algorithms: Discrete Fourier Transform, Fast Fourier Transform

Representation Learning is a growing community that tries to optimize which features are important. Manifold learning is trying to learn the shape of a lower-dimensional field, then you can work within that lower-dimensional, easier plane

** Models of Feature selection
Filter Model: set all features $\to$ selecting best subset $\to$ learning algorithm $\to$ performance

Wrapper Model: set of all features $\to$ Selecting best subset by looping (generating a subset $\iff$ learning algorithm) $\to$ performance

*** Stepwise Forward selection
- Wrapper method
- Exponential

Method: Add one feature at a time, evaluate a model with the new feature, calculate performance. Keep the subset of features that give you the best performance


*** Stepwise Backward selection
- Wrapper method
- Quadratic runtime

Method: Start with entire feature set, remove one at a time, calculate performance. Keep the smallest subset of features that give you the best performance


** Local Search Methods
Consider searching over the full space of possible features rather than adding or eliminating fores one at a time in a greedy fashion. It is referred to local each since it makes local modifications to a complete solution

*** Hill Climbing
- Start at in initial point in the search space. Look around the local neighborhood. Choose a way, see if performance improved, and take the step up if it did. You can add a /stochastic/ aspect by randomly selecting and flipping a bit in the vector, then checking performance after.


*** Simulated Annealing

It's like hill climbing, but you have a "temperature" that slowly decreases over time. If the temperature is high, the probability is more likely to choose a random step regardless of performance. The temperature slowly decreases over time, allowing the hill climbing to vary less until it converges.

*** Genetic algorithm

Suppose you have a vector $\mathcal{F}= \beta_{0},\beta_{1},\beta_{2},\beta_{3},\beta_{4},\beta_{5}$

We can refer to this vector as a genome. betas can be on and off, and there is another vector of functions that, when $\mathcal{F}[x]$ is 1, the function is activated. 


**** Selection and replacement

- Fitness Proportionate Selection
\[
  P(X_{i}) = \frac{f(X_{i})}{\sum_{j=1}^{n-1} f(X_{j})}
\]

Fitness is based on performance of the model trained with the subset of features

**** Recombination/Crossover

A method of mating two (or more) parents selected from the population. We assume two parents are generate two offspring by splicing the parent chromosomes, then mixing/matching the splices. This shouldnt occur ine very instance, it should be a probability.

**** Mutation
Introduce a random variation for a point in the offspring. There is a small probability a mutation occurs to slightly alter the data. Then, there is a hyper-mutation, which has a very small chance, but it can significantly change the offspring.





*** Principal Component Analysis (PCA)

To calculate $k$, you can calculate the /Proportion of Variance/.

You can use a scree graph

**** Finding the linear discriminants 

{{{hl(orange,COME BACK LATER)}}}


* Clustering

Expectation Maximization: a local search method that uses a max-likelihood approach.

kmeans, kmeans++, 

Theory says kmeans++ guarantees results will be O(log(k))-competitive relative to the optimzal clustering








