#+TITLE: Memory Management
#+AUTHOR: Ben Heinze
#+DATE: 2026-08-31
#+STARTUP: noindent

#+MACRO: hl @@html:<span class="hl-$1">$2</span>@@@@latex:\hl{$1}{$2}@@

# This is used to shrink the pdf page margins
#+LATEX_HEADER: \usepackage[left=0.75in,right=0.75in,top=1in,bottom=1in]{geometry}

# This is used to shrink the spacing between bullet points
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[itemize]{itemsep=2pt, topsep=4pt}

* Uniprogramming
Early memory management systems 
- early computer systems supported one user and one program at a time (aka /uniprogramming/)
- To execute a program, the entire program had to be loaded continuously into main memory
- What are the implications?
  - Lots of wasted resources when waiting
  - Memory constraints are inefficient

* Multiprogramming

In a /multiprogramming/ system, the user portion of memory must be divided to accommodate multiple processes.
- OS dynamically manages this division of memory (aka memory management)
- /Memory management/ (MM) determines how memory is allocated and used by different processes.


* Memory Management Requirements


** Relocation

/Relocation: Ability to load program to any available part of the main memory. Access memory locations regardless of where its loaded./
- in multiprogramming system, available memory is shared among multiple processes
- Typically, programmers do not know in where the program will be in the main memory in advance
- Active processes need to be able to be swapped in/out of main memory in order to maximize processor utilization

This memory management requirement raises a lot of technical problems

He shows figure 7.1: addressing requirements for a process

** Protection

/Protection: Ensure memory space allocated to the process you're running cant be accessed by unauthorized programs/

- Each process needs to be protected against unwanted access y other programs
- Relocation requirement makes harder to enforce protection since location of a program in main memory is unpredictable
- memory references generated by process must be checked at run time


** Sharing

- Sharing: allowing multiple programs/users to access common memory areas efficiently

he skipped over the deep dive for this one

** Logical Organization
/Logical organization: structuring memory to support program modularity (e.g., separating code, data, and stack) for easier development and execution./


he skipped over the deep dive for this one

** Physical Organization
/Physical organization: Managing the actual hardware memory (RAM, registers) to allocate and deallocate contiguous or non-contiguous blocks efficiently, addressing fragmentation challenges in early systems and optimizing resource use in modern ones/

- In earlier systems, the OS didn't have ability to move main program to from main memory to secondary memory. they used /overlaying/ where different program sections were loaded into the same memory... *(check notes later)*



* Fixed Partitioning


Fixed Partitioning Idea: partition memory into set of fixed partitions

First, assume the OS occupies portion of main memory, and the rest of the main memory is available for use by multiple processes
- two ways to partition memory:
  1. Equal sized partitions
  2. Variable sized partitions
- Any process whose size $\leq$ partition size can be loaded into the available partition. 
- if partitions are full, and process is ready or in running state, the OS can swap a process out of any partition and loaded another process

He shows figure 7.2: example of fixed partitioning of a 64-Mbyte memory. One block is equal sized, and the other is variable sized.

** Equal sized partitioning
- program could be larger than the partition: programmer must use overlays to handle this problem
- Regardless of the size of the program, the entire partition is used by a particular process
- /internal fragmentation/: if you have a lot of small programs running, space is not utilized properly

** Unequal sized partitioning
- Larger programs can be handled properly
- slightly better at handling smaller programs since we do have smaller partitions
- Can still have internal fragmentation

* Placement Algorithms
How can we place programs into these partitions?

For equal sized partitions, as long as there is a free partition, you can load the program into it. If there are no available partitions swap a process already int the main memory to the secondary storage and load the new program to that partition

For unequal sized partitioning, assign the new process to the smallest available partition
- Use a scheduling queue for each partition, where each corresponding process will wait in the queue for the partition
- efficient in terms of low fragmentation, but (check notes later)

He shows an example where there are four partitions of varying sizes. The goal is to minimize internal fragmentation, but it doesn't efficiently utilize main memory, since programs are only being loaded based on size and not taking into account of available partitions.
