#+TITLE: Memory Management
#+AUTHOR: Ben Heinze
#+DATE: 2026-08-31
#+STARTUP: noindent

#+MACRO: hl @@html:<span class="hl-$1">$2</span>@@@@latex:\hl{$1}{$2}@@

# This is used to shrink the pdf page margins
#+LATEX_HEADER: \usepackage[left=0.75in,right=0.75in,top=1in,bottom=1in]{geometry}

# This is used to shrink the spacing between bullet points
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[itemize]{itemsep=2pt, topsep=4pt}


#+begin_export html
<embed src="Memory Management.pdf" width="100%" height="800px" type="application/pdf">
#+end_export


* Uniprogramming
Early memory management systems 
- early computer systems supported one user and one program at a time (aka /uniprogramming/)
- To execute a program, the entire program had to be loaded continuously into main memory
- What are the implications?
  - Lots of wasted resources when waiting
  - Memory constraints are inefficient

* Multiprogramming

In a /multiprogramming/ system, the user portion of memory must be divided to accommodate multiple processes.
- OS dynamically manages this division of memory (aka memory management)
- /Memory management/ (MM) determines how memory is allocated and used by different processes.


* Memory Management Requirements


** Relocation

/Relocation: Ability to load program to any available part of the main memory. Access memory locations regardless of where its loaded./
- in multiprogramming system, available memory is shared among multiple processes
- Typically, programmers do not know in where the program will be in the main memory in advance
- Active processes need to be able to be swapped in/out of main memory in order to maximize processor utilization

This memory management requirement raises a lot of technical problems

He shows figure 7.1: addressing requirements for a process

** Protection

/Protection: Ensure memory space allocated to the process you're running cant be accessed by unauthorized programs/

- Each process needs to be protected against unwanted access y other programs
- Relocation requirement makes harder to enforce protection since location of a program in main memory is unpredictable
- memory references generated by process must be checked at run time


** Sharing

- Sharing: allowing multiple programs/users to access common memory areas efficiently

he skipped over the deep dive for this one

** Logical Organization
/Logical organization: structuring memory to support program modularity (e.g., separating code, data, and stack) for easier development and execution./


he skipped over the deep dive for this one

** Physical Organization
/Physical organization: Managing the actual hardware memory (RAM, registers) to allocate and deallocate contiguous or non-contiguous blocks efficiently, addressing fragmentation challenges in early systems and optimizing resource use in modern ones/

- In earlier systems, the OS didn't have ability to move main program to from main memory to secondary memory. they used /overlaying/ where different program sections were loaded into the same memory... *(check notes later)*



* Fixed Partitioning


Fixed Partitioning Idea: partition memory into set of fixed partitions

First, assume the OS occupies portion of main memory, and the rest of the main memory is available for use by multiple processes
- two ways to partition memory:
  1. Equal sized partitions
  2. Variable sized partitions
- Any process whose size $\leq$ partition size can be loaded into the available partition. 
- if partitions are full, and process is ready or in running state, the OS can swap a process out of any partition and loaded another process

He shows figure 7.2: example of fixed partitioning of a 64-Mbyte memory. One block is equal sized, and the other is variable sized.

** Equal sized partitioning
- program could be larger than the partition: programmer must use overlays to handle this problem
- Regardless of the size of the program, the entire partition is used by a particular process
- /internal fragmentation/: if you have a lot of small programs running, space is not utilized properly

** Unequal sized partitioning
- Larger programs can be handled properly
- slightly better at handling smaller programs since we do have smaller partitions
- Can still have internal fragmentation

** Disadvantages
- If your program is larger than all of the partitions, then {{{hl(red,overlays)}}} must be used
- {{{hl(red,internal fragmentation)}}}
- number of partitions specified at system generation time limits the number of active (not suspended) processes in the system


For equal sized partitions, as long as there is a free partition, you can load the program into it. If there are no available partitions swap a process already int the main memory to the secondary storage and load the new program to that partition

For unequal sized partitioning, assign the new process to the smallest available partition
- Use a scheduling queue for each partition, where each corresponding process will wait in the queue for the partition
- efficient in terms of low fragmentation, but (check notes later)

He shows an example where there are four partitions of varying sizes. The goal is to minimize internal fragmentation, but it doesn't efficiently utilize main memory, since programs are only being loaded based on size and not taking into account of available partitions.




* Dynamic Partitioning

To overcome some problems in fixed partitioning, dynamic partitioning was introduced.

Partitions are of variable length and number. 
- When a process is brought to memory, it is allocated exactly as much memory it requires 

OS needs to keep track of boundaries of the partitions 

/What happens when we use this strategy?/  
- *External Fragmentation*: You will  see a lot of small holes in the main memory which cannot be occupied by processes.
  - To remove this, we use /compaction/, which squishes the processes in the main memory to remove the gaps in memory, giving you one continuous free space rather than small holes between the processes.

** Dynamic Placement Algorithms 

Since compaction is time consuming and resource hungry the OS needs to be clever when choosing the best position for a process to reside in dynamic partitioning

| Algorithm | Description | Worst case |
| Best-fit  | Chooses the block that is closest in size to the request        | $O(n)$. | 
| First-fit | Begings to scan memory from the beginning and pics the first free hole the process will fit in | Worst one since it will quickly leave very small holes in memory, which requires compaction sooner than later|
| Next-fit  | begins to scan memory from the location of the last placement and chooses the next available block that is large enough. Once it reaches the end, it will go back to the beginning of the main memory (like best-fit but resumes from the last allocation) | Best option out of the three|


* Buddy system
- Combination of fixed and dynamic partitioning schemes.
- {{{hl(orange,Read about this scheme in the book, will be on quiz)}}}


* Memory Deallocation

When the partitions are not used anymore, they should be released.

** Fixed partitions
Reset the free/busy status of the partition

| Partition # | Starting | End | Action (binary if process is used or not) |
| 0           | -        | -   | 0                                         |
| 1           | -        | -   | 1                                         |
| 2           | -        | -   | 0                                         |
| 3           | -        | -   | 1                                         |
| 4           | -        | -   | 1                                         |


** Dynamic Partition

Need to combine the free areas

/Question: does the schemes we looked at provide a way to overcome problems arising from relocation requirement?/

* Relocation - fixed vs Dynamic Partitioning 
- A process will not always occupy the same place in memory over its lifetime 
  - 
- Dynamic partitioning $\to$ relocation is *always* required
{{{hl(orange,COME BACK LATER)}}}
- Fixed Partitioning $\to$ relocation is required *only if* a process can be reassigned to a different partition
{{{hl(orange,COME BACK LATER)}}}
- Consequence: The addresses a process references are *not fixed*
{{{hl(orange,COME BACK LATER)}}}

* Types of Addresses 

| Type                 | Description                                                                                                          |
| Physical or Absolute | Actual location in main memory                                                                                       |
| Logical              | Reference to a memory location independent of the current assignment of data to memory                               |
| Relative             | A particular example of logical address, in which the address is expressed as a location relative to some kown point |

* Relative Addressing 

- Memory reference in a loaded process are relative to the origin of the program
- Hardware mechanism to translate relative addresses to physical addresses
  - *Bounds register*: ending location of the program
  - *Base register*: starting address of the running program

He shows a diagram of hardware support for relocation


Both unequal fixed-size and variable-size partitioning schemes use memory inefficiently
- /Fixed/: internal fragmentation (wasted space inside a partition)
- /Variable/: external fragmentation (holes between allocations)

/Paging/ eliminates external fragmentation and limits internal fragmentation.

* Memory Management terms

| Term | Def |
| Frame | Fixed-length block of memory |
| Page  | fixed-length block of data that resides in secondary memory (such as a disk). A page of data may temporarily be copied into a frame of main memory. Paging doesn't require consecutive frames, so it's able to fill in the gaps (Hence elimiating external fragmentation)|
| Segment       | A variable-length block of data that resides in secondary memory. An entire segment may temporarily be copied into an available region of memory (segmentaiton) or the segment may be divided into pages which can be individually copied into main memory (combined segmentation and paging |




** Page Table

Maintained by OS, one for each process
- Maps each page in the process to the frames that it holds
  - (/page number $\to$ frame number/)
- Accessed by the processor via hardware mechanism that points to the current process's page table
- Used by processor to translate logical address into a physical address at runtime
- page (and frame) size is always a power of 2 
  - easier to convert logical $\to$ physical address
  - $\left[ \log_{2} \text{pages-size} \right] =$ the number of memory locations you have in a page, this is the maximum number of pages you can have in a process. If you have 16-bit address with a page size of 1kb, you'd have $\left[ \log_{2} 1024 = 10 \right]$ pages.

** Segmentation

A program can be subdivided into segments
- vary in length
- there's a max length

Segment table to represent the starting location and size of each segment loaded into the main memory 

Addressing consists of two parts:
1. Segment number
2. Offset

Similar to dynamic partitioning. Eliminates internal fragmentation

- Visible to the programmer, unlike paging which is invisible
- provided as a convenience for organizing programs and data logically
- programmer or compiler assigns code and data to different segments (code, stack, heap, globals, etc)
- For modular programming, code/data may be split further into multiple segments
- Main drawback: Programmer must stay aware of the /maximum segments size/



*** Addressing 
- No simple relationship between logical addresses and physical addresses:
1. Extract segment number
2. Use number to access process's segment table to find starting physical address of the segment
3. compare offset, express rightmost /m/ bits. If offset $\geq$ segment, it is invalid
4. {{{hl(orange,COME BACK LATER)}}}















